### ISSUE TITLE
Doesn't work without a session

### ISSUE THREAD

**Issue by Adirelle** [dunglas/DunglasAngularCsrfBundle#20]
As the bundle uses Symfony's CsrfTokenManager, which in turn relies on session, it doesn't work without a session. This prevents using it with stateless authentication, like JWT. Would it be possible to provide a CsrfTokenManager that doesn't rely on a session ?

By the way, if I understand AngularJS XSRF protection, the server should just ensure that the header matches the cookie (since both are sent), and maybe that it isn't forged.

**Comment by dunglas** [comment]
You don't need such token system when using JWT because the `Bearer` header is basically stored in local storage (and not in a cookie) and added in JavaScript to AJAX requests. JWT doesn't require a session because the public token is a signed with a private key known only by the server.

The server should set a cookie named `XSRF-TOKEN` containing a token, then Angular will a a new header called `X-XSRF-TOKEN` to all AJAX requests it does. The server should verify that the cookie in the header match the token sent previously trough the cookie. It's exactly what this bundle does and it requires a session to do that.

**Comment by Adirelle** [comment]
Technically, local storage is vulnerable to XSS attacks, so is the JWT. However, it is probably easier to deal with XSS than XSRF. Anyway, I could probably write an AngularCsrfTokenManager that would use the JWT implementation to create and check XSRF tokens.

Thanks you for your time.
