### ISSUE TITLE
Is this still needed for api-platform?

### ISSUE THREAD

**Issue by supersexy** [dunglas/DunglasAngularCsrfBundle#60]
I am confused - is this bundle still needed for api-platform? 
Is it true that api-platform does not come with csrf protection out of the box???

**Comment by tkerst** [comment]
According to the API Platform Docs, only raw documents are supported as request input by default. It also says: "Adding support for application/x-www-form-urlencoded makes your API vulnerable to CSRF attacks. Be sure to enable proper countermeasures such as DunglasAngularCsrfBundle." [[1]](https://api-platform.com/docs/core/form-data/)

For a CSRF attack, one of the content types 
- "application/x-www-form-urlencoded", 
- "text/plain" or
- "multipart/form-data" 

is needed to be supported since these skip the CORS preflight which would prevent access from the bad origin [[2]](https://www.sjoerdlangkemper.nl/2019/01/09/csrf/). Allowed origins in API Platform can be set via environment variable (CORS_ALLOW_ORIGIN) or in "nelmio_cors.yaml". This of course needs nelmio/cors-bundle installed, which I think is done by default.

The first two of the listed content types are disabled by default [[1]](https://api-platform.com/docs/core/form-data/)[[3]](https://github.com/api-platform/core/blob/master/features/security/validate_incoming_content-types.feature), the third one is, as far as I found, only used by the GraphQL entrypoint [[4]](https://github.com/api-platform/core/pull/3041). 

Thus, you should be safe in most cases but when enabling one of the listed content types, you should use this bundle.
