### ISSUE TITLE
Allow Symfony 5 

### ISSUE THREAD

**Issue by pasqualepalmaccio** [dunglas/DunglasAngularCsrfBundle#70]
Please allow support for symfony 5. We can't migrate to 5 without this bundle.

**Comment by jmontoyaa** [comment]
Any news about this issue?

**Comment by jmontoyaa** [comment]
Problem seems to be v4 of  phpspec/phpspec package ... 

https://packagist.org/packages/phpspec/phpspec#4.3.4

**Comment by jmontoyaa** [comment]
Related to https://github.com/dunglas/DunglasAngularCsrfBundle/pull/65

**Comment by dneustadt** [comment]
Since this bundle has unfortunately not been updated in quite a while, I thought it was fair game to take inspiration and create a new bundle with basically the same functionality:
[https://github.com/dneustadt/DneustadtCsrfCookieBundle](https://github.com/dneustadt/DneustadtCsrfCookieBundle)

I incorporated ideas and fixes for Symfony 5 from open pull requests and issues. Configuration of routes is done through defaults with the possibility of using ExpressionLanguage to determine token creation and/or requirements.

I hope this is ok @dunglas

**Comment by dunglas** [comment]
@dneustadt no problem! You're very welcome.

With the rise of the SameSite cookies and of the Origin header in modern browsers, this bundle isn't useful anymore.

I'll archive it and point to your repo for people wanting to support old browsers.
